# Project information
site_name: Codacy documentation
site_url: https://pauloribeiro-codacy.github.io/codacy-docs-poc/

# Configuration
theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'images/codacy-logo.png'

  extra_css:
  - 'css/extra.css'

# Repository
repo_name: 'pauloribeiro-codacy/codacy-docs-poc'
repo_url: 'https://github.com/pauloribeiro-codacy/codacy-docs-poc'

# Copyright
copyright: 'Â© <a href="https://www.codacy.com">Codacy</a>'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: True
  - meta

# Table of contents
#nav:
#  - Home: 'index.md'
#  - Getting started:
#      - 'getting-started/getting-started.md'
#      - 'getting-started/repository-add.md'
#      - 'getting-started/account-permissions.md'
#      - 'getting-started/repository-setup.md'
#      - 'getting-started/supported-languages.md'
