grafana:
  enabled: true
  adminPassword: <--- admin user password --->
  sidecar:
    dashboards:
      searchNamespace: ALL
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100/
      version: 1
      orgId: 1
      access: proxy
      basicAuth: false
      editable: true
      jsonData:
         tlsSkipVerify: true
    - name: Prometheus
      type: prometheus
      url: http://prometheus-prometheus-oper-prometheus:9090/
      version: 1
      orgId: 1
      access: proxy
      basicAuth: false
      editable: true
      jsonData:
         tlsSkipVerify: true

prometheusOperator:
  createCustomResource: false
  tlsProxy:
    enabled: false
  admissionWebhooks:
    enabled: false

prometheus:
  thanos:
    service:
      enabled: false
  service:
    sessionAffinity: "ClientIP"
  prometheusSpec:
    replicas: 1
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    walCompression: true